list_assets_and_prices:
  path: /list
  methods: [ GET ]
  controller: App\Controller\ApiController::saveAsset

get_assets_api:
  path: /api/assets
  methods: [ GET ]
  controller: App\Controller\ApiController::getAssets

render_assets:
  path: /show
  methods: [ GET ]
  controller: App\Controller\ApiController::showAssets